services:
  teacher-story:
    container_name: teacher-story-godot
    image: ghcr.io/${GITHUB_REPOSITORY:-cmnemoi/teacher-story-godot}:${IMAGE_TAG:-main}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.teacher-story.rule=Host(`${DOMAIN:-teacher-story.cmnemoi.com}`)
      - traefik.http.routers.teacher-story.entrypoints=websecure
      - traefik.http.routers.teacher-story.tls.certresolver=letsencrypt
      - traefik.http.services.teacher-story.loadbalancer.server.port=8080
      # Middleware pour les headers CORS (nécessaire pour Godot WebGL)
      - traefik.http.middlewares.teacher-story-cors.headers.customrequestheaders.Cross-Origin-Opener-Policy=same-origin
      - traefik.http.middlewares.teacher-story-cors.headers.customrequestheaders.Cross-Origin-Embedder-Policy=require-corp
      - traefik.http.routers.teacher-story.middlewares=teacher-story-cors@docker
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
